version: '3'
services:
    page-indexer:
        build: .
        image: page-indexer
        command: page-indexer
        expose:
            - "1234"
    nginx:
        build: ./nginx
        image: nginx
        ports:
            - "8080:80"
        depends_on:
            - page-indexer
